/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cargo_Mysql;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;

/**
 *
 * @author abdir
 */
public class cargo_Mysql extends javax.swing.JFrame {

    
    private static final String username ="root";
    private static final String password ="ckeccy2";
    private static final String dataConn ="jdbc:mysql://localhost:3306/connector";
    
    Connection sqlConn =null;
    PreparedStatement pst =null;
    ResultSet rs = null;
    int q, i ,id, deleteItem;
    
    
    public cargo_Mysql() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //=============//
    public void upDateDB(){
        try
        {
        Class.forName("com.mysql.jdbc.Driver");  
        sqlConn =DriverManager.getConnection(dataConn,username,password);
        pst = sqlConn.prepareStatement("select * from connector");
        
        rs = pst.executeQuery();
        ResultSetMetaData stData = rs.getMetaData();
        
        q= stData.getColumnCount();
        
        DefaultTableModel RecordTable =(DefaultTableModel)jTable1.getModel();
        RecordTable.setRowCount(0);   
        
        while(rs.next()){
            Vector columnData = new Vector();
            
            for (i =1;i <=q; i++)
            {
                columnData.add(rs.getShort("ID"));
                columnData.add(rs.getShort("CustomerID"));
                columnData.add(rs.getShort("Firstname"));
                columnData.add(rs.getShort("Lastname"));
                columnData.add(rs.getShort("Address"));
                columnData.add(rs.getShort("PostCode"));
                columnData.add(rs.getShort("Telephone"));
            }
            RecordTable.addRow(columnData);
        }
    }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
        //+============================//
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtnUpdate = new java.awt.Button();
        jbtnPrint = new java.awt.Button();
        jbtnReset = new java.awt.Button();
        jbtnDelete = new java.awt.Button();
        jbtnExit = new java.awt.Button();
        jbtnAddNew = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtPostCode = new javax.swing.JTextField();
        jtxtLastname = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtTelephone = new javax.swing.JTextField();
        jtxtCustomerID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnUpdate.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnUpdate.setLabel("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 180, -1));

        jbtnPrint.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnPrint.setLabel("Print");
        jPanel2.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 220, 180, -1));

        jbtnReset.setActionCommand("Reset");
        jbtnReset.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnReset.setLabel("Rest");
        jbtnReset.setName("Reset"); // NOI18N
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 290, 180, -1));

        jbtnDelete.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnDelete.setLabel("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 180, -1));

        jbtnExit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnExit.setLabel("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 180, -1));

        jbtnAddNew.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbtnAddNew.setLabel("Add New ");
        jbtnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddNewActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 180, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 260, 530));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Telephone");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jtxtFirstname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstnameActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 85, 280, 30));

        jtxtPostCode.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtPostCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPostCodeActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 280, -1));

        jtxtLastname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(jtxtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 280, -1));

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 280, -1));

        jtxtTelephone.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(jtxtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 280, -1));

        jtxtCustomerID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(jtxtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 280, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Post Code");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Address");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Lastname");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("CustomermID");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Firstname");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Customer ID", "Firstname", "Lastname", "Address", "Post Code", "Telephone"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 560, 190));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 660, 530));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Cargo Request");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 530, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 910, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 960, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {                                         

        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to rxit", "MySQL connector",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        // TODO add your handling code here:
    }                                        

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jtxtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jtxtPostCodeActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {                                          

        jtxtCustomerID.setText("");
        jtxtFirstname.setText("");
        jtxtLastname.setText("");
        jtxtAddress.setText("");
        jtxtPostCode.setText("");
        jtxtTelephone.setText("");

// TODO add your handling code here:
    }                                         

    private void jbtnAddNewActionPerformed(java.awt.event.ActionEvent evt) {                                           
 try
        {
        Class.forName("com.mysql.jdbc.Driver");  
        sqlConn =DriverManager.getConnection(dataConn,username,password);
        pst = sqlConn.prepareStatement("insert into connector(CustomerID=? ,Firstname=? ,Lastname=? ,Address=?,PostCode=?,Telephone=? where id=?");
        
        
        pst.setString(1, jtxtCustomerID.getText());
        pst.setString(2, jtxtFirstname.getText());
        pst.setString(3, jtxtLastname.getText());
        pst.setString(4, jtxtAddress.getText());
        pst.setString(5, jtxtPostCode.getText());
        pst.setString(6, jtxtTelephone.getText());
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Record updated");
        upDateDB();
        }
 catch(ClassNotFoundException ex){
     java.util.logging.Logger.getLogger(cargo_Mysql.class.getName()).log(java.util.logging.Level.SEVERE,null, ex);
 }catch(SQLException ex){
             java.util.logging.Logger.getLogger(cargo_Mysql.class.getName()).log(java.util.logging.Level.SEVERE,null, ex);

    }
        
        
// TODO add your handling code here:
    }                                          

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cargo_Mysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cargo_Mysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cargo_Mysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cargo_Mysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cargo_Mysql().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Button jbtnAddNew;
    private java.awt.Button jbtnDelete;
    private java.awt.Button jbtnExit;
    private java.awt.Button jbtnPrint;
    private java.awt.Button jbtnReset;
    private java.awt.Button jbtnUpdate;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtCustomerID;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtLastname;
    private javax.swing.JTextField jtxtPostCode;
    private javax.swing.JTextField jtxtTelephone;
    // End of variables declaration                   
}
